version: "3.8"
services:
  fastapi:
    build: ./fastapi
    ports:
      - 5000:5000
    volumes:
      - ./fastapi:/app:Z
  sveltekit:
    build: ./sveltekit
    ports:
      - 3000:3000
    volumes:
      - ./sveltekit:/app:Z
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
